include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [test/models/**]
  language:
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    always_put_required_named_parameters_first: true
    always_use_package_imports: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_dynamic_calls: true
    avoid_escaping_inner_quotes: true
    avoid_positional_boolean_parameters: true
    avoid_slow_async_io: true
    avoid_unused_constructor_parameters: true
    cancel_subscriptions: true
    cast_nullable_to_non_nullable: true
    close_sinks: true
    discarded_futures: true
    do_not_use_environment: true
    literal_only_boolean_expressions: true
    matching_super_parameters: true
    missing_whitespace_between_adjacent_strings: true
    no_literal_bool_comparisons: true
    no_runtimeType_toString: true
    no_self_assignments: true
    noop_primitive_operations: true
    only_throw_errors: true
    parameter_assignments: true
    prefer_asserts_with_message: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_constructors_over_static_methods: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_null_aware_method_calls: true
    prefer_single_quotes: true
    require_trailing_commas: true
    sized_box_shrink_expand: true
    test_types_in_equals: true
    unawaited_futures: true
    unnecessary_await_in_return: true
    unnecessary_statements: true
    use_colored_box: true
    use_decorated_box: false
    use_enums: true
    use_is_even_rather_than_modulo: true
    use_named_constants: true